-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:40:20 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CabRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CabRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CabRental` DEFAULT CHARACTER SET utf8 ;
USE `CabRental` ;

-- -----------------------------------------------------
-- Table `CabRental`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CabRental`.`driver` (
  `driver_id` INT NOT NULL,
  `driver_fname` VARCHAR(45) NOT NULL,
  `driver_lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`driver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CabRental`.`cabs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CabRental`.`cabs` (
  `cab_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  PRIMARY KEY (`cab_id`, `driver_id`),
  INDEX `fk_cabs_1_idx` (`driver_id` ASC),
  CONSTRAINT `fk_cabs_1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `CabRental`.`driver` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CabRental`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CabRental`.`customer` (
  `customer_otp` INT NOT NULL,
  `customer_fname` VARCHAR(45) NOT NULL,
  `cab_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`customer_otp`),
  INDEX `fk_customer_1_idx` (`cab_id` ASC),
  UNIQUE INDEX `unique` (`cab_id` ASC, `timestamp` ASC),
  CONSTRAINT `fk_customer_1`
    FOREIGN KEY (`cab_id`)
    REFERENCES `CabRental`.`cabs` (`cab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
