-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 03:29:56 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Ecommerce`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`supplier` (
  `supplier_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`customer` (
  `customer_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`order` (
  `order_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_1_idx` (`supplier_id` ASC),
  INDEX `fk_order_2_idx` (`customer_id` ASC),
  CONSTRAINT `fk_order_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Ecommerce`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Ecommerce`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`item` (
  `item_id` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`order-item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`order-item` (
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `item_id`),
  INDEX `fk_order-item_2_idx` (`item_id` ASC),
  INDEX `fk_order-item_3_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_order-item_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ecommerce`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order-item_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `Ecommerce`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order-item_3`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Ecommerce`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
