-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:41:42 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FoodDelivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FoodDelivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FoodDelivery` DEFAULT CHARACTER SET utf8 ;
USE `FoodDelivery` ;

-- -----------------------------------------------------
-- Table `FoodDelivery`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodDelivery`.`customer` (
  `customer_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDelivery`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodDelivery`.`restaurant` (
  `restaurant_id` INT NOT NULL,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `restaurant_items` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDelivery`.`deliverer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodDelivery`.`deliverer` (
  `deliverer_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deliverer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDelivery`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodDelivery`.`order` (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `deliverer_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_1_idx` (`customer_id` ASC),
  INDEX `fk_order_2_idx` (`deliverer_id` ASC),
  INDEX `fk_order_3_idx` (`restaurant_id` ASC),
  UNIQUE INDEX `unique` (`customer_id` ASC, `timestamp` ASC),
  CONSTRAINT `fk_order_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `FoodDelivery`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_2`
    FOREIGN KEY (`deliverer_id`)
    REFERENCES `FoodDelivery`.`deliverer` (`deliverer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_3`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `FoodDelivery`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
