-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:44:26 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HotelBooking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HotelBooking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelBooking` DEFAULT CHARACTER SET utf8 ;
USE `HotelBooking` ;

-- -----------------------------------------------------
-- Table `HotelBooking`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`hotel` (
  `hotel_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hotel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBooking`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`customer` (
  `customer_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HotelBooking`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`booking` (
  `booking_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `isLoyal` TINYINT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_booking_1_idx` (`customer_id` ASC),
  INDEX `fk_booking_2_idx` (`hotel_id` ASC),
  UNIQUE INDEX `unique` (`customer_id` ASC, `timestamp` ASC),
  CONSTRAINT `fk_booking_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `HotelBooking`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_2`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `HotelBooking`.`hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
