-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:42:24 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IMDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IMDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IMDB` DEFAULT CHARACTER SET utf8 ;
USE `IMDB` ;

-- -----------------------------------------------------
-- Table `IMDB`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMDB`.`actor` (
  `actor_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMDB`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMDB`.`movie` (
  `movie_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lead_actor_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`),
  INDEX `fk_movie_1_idx` (`lead_actor_id` ASC),
  CONSTRAINT `fk_movie_1`
    FOREIGN KEY (`lead_actor_id`)
    REFERENCES `IMDB`.`actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IMDB`.`tvSeries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IMDB`.`tvSeries` (
  `tvs_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lead_actor_id` INT NOT NULL,
  PRIMARY KEY (`tvs_id`),
  INDEX `fk_tvSeries_1_idx` (`lead_actor_id` ASC),
  CONSTRAINT `fk_tvSeries_1`
    FOREIGN KEY (`lead_actor_id`)
    REFERENCES `IMDB`.`actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
