-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:41:00 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IRCTC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IRCTC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IRCTC` DEFAULT CHARACTER SET utf8 ;
USE `IRCTC` ;

-- -----------------------------------------------------
-- Table `IRCTC`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`train` (
  `train_id` INT NOT NULL,
  `train_num` INT NOT NULL,
  PRIMARY KEY (`train_id`, `train_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IRCTC`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IRCTC`.`ticket` (
  `ticket_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `train_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `isReserved` TINYINT NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_ticket_1_idx` (`customer_id` ASC),
  INDEX `fk_ticket_2_idx` (`train_id` ASC),
  UNIQUE INDEX `unique` (`customer_id` ASC, `timestamp` ASC),
  CONSTRAINT `fk_ticket_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `IRCTC`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_2`
    FOREIGN KEY (`train_id`)
    REFERENCES `IRCTC`.`train` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
