-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 02:41:48 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Paytm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Paytm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Paytm` DEFAULT CHARACTER SET utf8 ;
USE `Paytm` ;

-- -----------------------------------------------------
-- Table `Paytm`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paytm`.`branch` (
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paytm`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paytm`.`account` (
  `account_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_account_1_idx` (`branch_id` ASC),
  INDEX `fk_account_2_idx` (`customer_id` ASC),
  UNIQUE INDEX `unique` (`branch_id` ASC, `customer_id` ASC),
  CONSTRAINT `fk_account_1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Paytm`.`branch` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Paytm`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paytm`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paytm`.`customer` (
  `customer_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_1_idx` (`account_id` ASC),
  CONSTRAINT `fk_customer_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Paytm`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
