-- MySQL Script generated by MySQL Workbench
-- Wednesday 27 September 2017 12:38:43 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjectsAndEmployees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjectsAndEmployees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectsAndEmployees` DEFAULT CHARACTER SET utf8 ;
USE `ProjectsAndEmployees` ;

-- -----------------------------------------------------
-- Table `ProjectsAndEmployees`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectsAndEmployees`.`project` (
  `project_id` INT NOT NULL,
  `pname` VARCHAR(45) NOT NULL,
  `pmanager_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_project_1_idx` (`pmanager_id` ASC),
  CONSTRAINT `fk_project_1`
    FOREIGN KEY (`pmanager_id`)
    REFERENCES `ProjectsAndEmployees`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectsAndEmployees`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjectsAndEmployees`.`employee` (
  `employee_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_1_idx` (`project_id` ASC),
  CONSTRAINT `fk_employee_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ProjectsAndEmployees`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
